---
title: "Paper 2, Econ 980x"
author: "Alice Chen"
date: "2022-11-27"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(ggplot2)
library(janitor)
library(ggthemes)
library(stargazer)
library(tinytex)
library(ipumsr)
library(dplyr)
library(haven)
library(survey)
library(spatstat)
library(kableExtra)
library(lfe)



```

```{r cashe data, cache = TRUE}

ddi <- read_ipums_ddi("atus_00005.xml")
csv <- read_ipums_micro(ddi) %>%
  clean_names()

```


```{r files}




data

#csv <- read_csv(file = "atus_00001.csv.gz") %>%
 # clean_names()

# race 
race_file <- read_excel("race_980x.xlsx")

race_file <- race_file %>%
  rename(code1 = race) %>%
  rename(race = code) 

csv <- left_join(csv, race_file, by = "race") %>%
  rename(race_code = race) %>%
  rename(race = code1)


# education
education_file <- read_excel("Education.xlsx")
education_file <- education_file %>%
  rename(code_educ = educ) %>%
  rename(educ = code_education) %>%
  mutate(educ = as.numeric(educ))

csv <- left_join(csv, education_file, by = "educ") %>%
  rename(code_education = educ) %>%
  rename(educ = code_educ) 

# marital status
marital_file <- read_excel("marital_status.xlsx")
education_file <- marital_file %>%
  mutate(marst = as.numeric(marst))
  
csv <- left_join(csv, marital_file, by = "marst") %>%
  rename(code_marst = marst) %>%
  rename(marst = marst_code) %>%
  mutate(marst_simple = ifelse(code_marst <= 2, "Married", ifelse(code_marst >= 6, "Never Married", "Separated/Divorced")))



# age
csv <- csv %>%
  filter(age > 18)

# children
csv <- csv %>%
  mutate(child = ifelse(yngch < 19, 1, 0) )

# gender

csv <- csv %>%
  mutate(gender = ifelse(sex == 1, "male", "female")) 

# years 

csv %>%
  summary(earnweek)

# employed
csv <- csv %>%
  mutate(empstat_cps8 = as.numeric(empstat_cps8)) %>%
  mutate(emp = ifelse(empstat_cps8<= 2, "Employed", ifelse(empstat_cps8>=5, "Not In Labour Force", "Unemployed")))

# race
csv %>%
  count(race, sort = TRUE) %>%
  filter(n > 1000)

#We can see that top 5 groups > 1000 people

csv <- csv %>%
  filter(race %in% c("White only", "Black only", "Asian only", "American Indian, Alaskan Native", "White-American Indian")) 

view(c)
```


```{r graphs}


#leisure hours aggregate
csv %>%
  ggplot(mapping = aes(x = bls_leis)) +
  geom_histogram(binwidth=50) +
  labs(
  title = "Distribution of daily individual leisure minutes",
  x = "Daily Minutes",
  y = "Count",
  caption = "Data from ATUS",
) 

csv %>%
  filter(year %in% c(2007, 2009)) %>%
  ggplot(mapping = aes(x = bls_leis)) +
  geom_histogram(binwidth=50) +
  facet_wrap(~year) +
  labs(
  title = "Distribution of daily individual leisure minutes",
  x = "Daily Minutes",
  y = "Count",
  caption = "Data from ATUS",
)



#leisure hours aggregate by gender
csv %>%
  filter(year < 2020) %>%
  group_by(gender) %>%
  ggplot(mapping = aes(x = bls_leis) )+
  geom_histogram(binwidth=50) +
  facet_wrap(~ gender) +
    labs(
  title = "Distribution of daily individual leisure minutes",
  x = "Daily Minutes",
  y = "Count",
  caption = "Data from ATUS",
)


csv %>%
  filter(year %in% c(2007, 2009)) %>%
  ggplot(mapping = aes(x = bls_leis)) +
  geom_histogram(binwidth=50) +
  facet_wrap(~ gender + year) +
  labs(
  title = "Distribution of daily individual leisure minutes",
  x = "Daily Minutes",
  y = "Count",
  caption = "Data from ATUS",
)




# Median
csv %>%
  filter(year < 2020) %>%
  group_by(gender, year) %>%
  summarize(median_leisure = weighted.median(bls_leis, as.numeric(wt06), na.rm=TRUE)) %>%
  clean_names() %>%
  ggplot(aes(x = year, y = median_leisure)) +
  geom_line() +
  facet_wrap(~ gender) +
  labs(
  title = "Median daily individual leisure minutes by gender",
  y = "Daily Minutes",
  x = "Year",
  caption = "Data from ATUS",
) 

# mean
csv %>%
  filter(year < 2020) %>%
  group_by(gender,year) %>%
  summarize(new = weighted.mean(bls_leis, wt06)) %>%
  clean_names() %>%
  ggplot(aes(x = year, y = new)) +
  geom_line() +
  facet_wrap(~ gender) +
  labs(
  title = "Weighted mean daily individual leisure minutes by gender",
  y = "Daily Minutes",
  x = "Year",
  caption = "Data from ATUS",
) 

# Median 
csv %>%
  filter(year > 2005) %>%
  filter(year < 2011) %>%
  group_by(year, gender) %>%
  summarize(median_bls_leis = weighted.median(bls_leis, wt06)) %>%
  clean_names() %>%
  ggplot(aes(x = year, y = median_bls_leis)) +
  geom_line() +
  facet_wrap(~ gender) +
  labs(
  title = "Weighted median daily individual leisure minutes by gender",
  y = "Daily Minutes",
  x = "Year",
  caption = "Data from ATUS",
) 

# Mean
csv %>%
  filter(year > 2005) %>%
  filter(year < 2011) %>%
  group_by(year, gender) %>%
  summarize(mean_bls_leis = weighted.mean(bls_leis, wt06)) %>%
  clean_names() %>%
  ggplot(aes(x = year, y = mean_bls_leis)) +
  geom_line() +
  facet_wrap(~ gender) +
  labs(
  title = "Mean daily individual leisure minutes by gender",
  y = "Daily Minutes",
  x = "Year",
  caption = "Data from ATUS",
) 

# All Quantile
csv %>%
  filter(year < 2020) %>%
  group_by(year, gender) %>%
  summarize(quantile_25 = weighted.quantile(bls_leis, wt06, prob = 0.25), quantile_50 = weighted.quantile(bls_leis, wt06, prob = 0.50), quantile_75 = weighted.quantile(bls_leis, wt06, prob = 0.75)) %>%
  clean_names() %>%
  pivot_longer(quantile_25:quantile_75, names_to = "quantile", values_to = "hours") %>%
  ggplot(aes(x = year, y = hours, group = quantile, colour = quantile)) +
  geom_line() +
    facet_wrap(~ gender) +
  labs(
  title = "Weighted daily individual leisure minutes by gender",
  y = "Daily Minutes",
  x = "Year",
  caption = "Data from ATUS",
) 

# by year, gender
csv %>%
  filter(year < 2020) %>%
  group_by(year, gender) %>%
  summarize(quantile_25 = weighted.quantile(bls_leis, wt06, prob = 0.25), quantile_50 = weighted.quantile(bls_leis, wt06, prob = 0.50), quantile_75 = weighted.quantile(bls_leis, wt06, prob = 0.75)) %>%
  clean_names() %>%
  pivot_longer(quantile_25:quantile_75, names_to = "quantile", values_to = "hours") %>%
  filter(year > 2005) %>%
  filter(year < 2011) %>%
  ggplot(aes(x = year, y = hours, group = quantile, colour = quantile)) +
  geom_line() +
  facet_wrap(~gender) +
    labs(
  title = "Weighted daily individual leisure minutes by gender",
  y = "Daily Minutes",
  x = "Year",
  caption = "Data from ATUS",
) 

# by year, gender
csv %>%
  group_by(year, gender) %>%
  summarize(median = median(bls_leis)) %>%
  clean_names() %>%
  filter(year > 2005) %>%
  filter(year < 2011) %>%
  ggplot(aes(x = year, y = median)) +
  geom_line() +
  facet_wrap(~gender) +
      labs(
  title = "Daily individual leisure minutes by gender",
  y = "Daily Minutes",
  x = "Year",
  caption = "Data from ATUS",
) 


#csv %>%
 # ggplot(mapping = aes(x = year, y = bls_leis)) + 
 # geom_jitter(alpha = 0.01)
  


```


```{r regressions}

#naive regression of men versus women
  

g <- csv %>%
  lm(formula = bls_leis ~ gender, weight = wt06)
summary(g)

#naive regression of men versus women + year 

y <- csv %>%
  lm(formula = bls_leis ~ gender + year, weight = wt06)

# race count
newcsv <- csv %>%
 filter(race_code <= 210)

newcsv
newcsv %>%
  lm(formula = bls_leis ~ gender + year + age + race, weight = wt06) 

# 
a <- newcsv %>%
  lm(formula = bls_leis ~ gender + year + age + race, weight = wt06) 
summary(a)

newcsv

# education
newcsv1 <- newcsv %>%
  mutate(new_educ = ifelse(code_education <= 17, "<High School", ifelse(code_education >= 40, ">Four Year Degree", "High School Graduate")))

  
b <- newcsv1 %>%
  lm(formula = bls_leis ~ gender + year + age + race + new_educ, weight = wt06) 
summary(b)


# with children
 

c <- newcsv1 %>%
  lm(formula = bls_leis ~ gender + year + age + race + new_educ + nchild, weight = wt06) 
summary(c)

#marital status

d <- newcsv1 %>%
  lm(formula = bls_leis ~ gender + year + age + race + new_educ + nchild + marst_simple, weight = wt06) 
summary(d)



```

```{r table0, results = "asis"}
stargazer(a, b, c, d, title="Various Models", align=TRUE, type = "html")
```




```{r employment}

newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2011) %>%
  group_by(year) %>%
  count(emp) %>%
  filter(emp == "Unemployed") %>%
  ggplot(mapping = aes(x = year, y = n)) +
  geom_line() +
  labs(
  title = "Unemployment",
  y = "Daily Minutes",
  x = "Count",
  caption = "Data from ATUS",
)
  #facet_wrap(~emp)

newcsv1 %>%
  ggplot(mapping = aes(x = bls_leis)) +
  geom_histogram() +
  facet_wrap(~emp) +
  labs(
  title = "Daily individual leisure minutes by employment type",
  y = "Count",
  x = "Daily Minutes",
  caption = "Data from ATUS",
)

newcsv1 %>%
  filter(year < 2020) %>%
  group_by(emp, gender, new_educ, year) %>%
  summarize(median = weighted.median(bls_leis, wt06)) %>%
  ggplot(mapping = aes(x = year, y = median, group = new_educ, colour = new_educ)) +
  geom_line() +
  facet_wrap(~gender + emp) +
  labs(
  title = "Weighted daily individual leisure minutes",
  y = "Daily Minutes",
  x = "Count",
  caption = "Data from ATUS",
)

newcsv1 %>%
  filter(year < 2020) %>%
  group_by(emp, gender, new_educ, year) %>%
  summarize(median = median(bls_leis)) %>%
  ggplot(mapping = aes(x = year, y = median, group = new_educ, colour = new_educ)) +
  geom_line() +
  facet_wrap(~gender + emp) +
  labs(
  title = "Daily individual leisure minutes",
  y = "Daily Minutes",
  x = "Count",
  caption = "Data from ATUS",
)
  
  
newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2011) %>%
  group_by(emp, gender, new_educ, year) %>%
  summarize(median = weighted.median(bls_leis, wt06)) %>%
  ggplot(mapping = aes(x = year, y = median, group = new_educ, colour = new_educ)) +
  geom_line() +
  facet_wrap(~gender + emp) +
  labs(
  title = "Weighted daily individual leisure minutes",
  y = "Daily Minutes",
  x = "Count",
  caption = "Data from ATUS",
)
  
newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2011) %>%
  group_by(emp, gender, new_educ, year) %>%
  summarize(median = median(bls_leis)) %>%
  ggplot(mapping = aes(x = year, y = median, group = new_educ, colour = new_educ)) +
  geom_line() +
  facet_wrap(~gender + emp) +
  labs(
  title = "Daily individual leisure minutes",
  y = "Daily Minutes",
  x = "Count",
  caption = "Data from ATUS",
)
  
  
count_table <- newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2011) %>%
  group_by(emp, gender) %>%
  tally()

count_table2 <- newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2011) %>%
  group_by(emp, gender, new_educ) %>%
  tally()
  
kable(count_table2) %>% kable_styling()
kable(count_table) %>% kable_styling()

```

```{r population_of_employment}

newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2011) %>%
  group_by(emp, year) %>%
  tally() %>%
  pivot_wider(names_from = year, values_from = n) %>%
  clean_names() %>%
  mutate(change_2008 = x2008-x2007) %>%
  mutate(change_2009 = x2009-x2008) %>%
  mutate(change_2010 = x2010-x2009) %>%
  select(1, 6:8) %>%
  kbl() %>%
  kable_styling()
  


```


```{r moremodels}
#Change

change <- newcsv1 %>%
  filter(year<2020) %>%
  group_by(gender,  year, new_educ, child, marst_simple) %>%
  summarize(median_bls_leis = weighted.median(bls_leis, wt06)) %>%
  clean_names() %>%
  pivot_wider(values_from = median_bls_leis, names_from = year) %>%
  clean_names() %>%
  mutate(leisure_change = x2009 - x2007)

change11 <- newcsv1 %>%
  filter(year<2020) %>%
  group_by(gender,  year, new_educ, child, marst_simple, emp) %>%
   summarize(median_bls_leis = weighted.median(bls_leis, wt06)) %>%
  clean_names() %>%
  pivot_wider(values_from = median_bls_leis, names_from = year) %>%
  clean_names() %>%
  mutate(leisure_change = x2009 - x2007)

change2 <- newcsv1 %>%
  filter(year<2020) %>%
  group_by(gender, year) %>%
  summarize(median_bls_leis = weighted.median(bls_leis, wt06)) %>%
  clean_names() %>%
  pivot_wider(values_from = median_bls_leis, names_from = year) %>%
  clean_names() %>%
  mutate(leisure_change = x2009 - x2007)

change3 <- newcsv1 %>%
  filter(year<2020) %>%
  group_by(gender,  year, new_educ, nchild, marst_simple) %>%
   summarize(median_bls_leis = weighted.median(bls_leis, wt06)) %>%
  clean_names() %>%
  pivot_wider(values_from = median_bls_leis, names_from = year) %>%
  clean_names() %>%
  mutate(leisure_change = x2009 - x2007)

change4 <- newcsv1 %>%
  filter(year<2020) %>%
  group_by(gender,  year, new_educ, nchild, marst_simple) %>%
  summarize(mean(bls_leis)) %>%
  clean_names() %>%
  pivot_wider(values_from = mean_bls_leis, names_from = year) %>%
  clean_names() %>%
  mutate(leisure_change = x2009 - x2007)


change12 <- newcsv1 %>%
  filter(year<2020) %>%
  group_by(gender,  year, emp) %>%
   summarize(median_bls_leis = weighted.median(bls_leis, wt06)) %>%
  clean_names() %>%
  pivot_wider(values_from = median_bls_leis, names_from = year) %>%
  clean_names() %>%
  mutate(leisure_change = x2009 - x2007)

#child
newcsv1




delta <- change %>%
  lm(formula = leisure_change ~ gender+ new_educ+ child+ marst_simple)
summary(delta)

delta11 <- change11 %>%
  lm(formula = leisure_change ~ gender+ new_educ+ child+ marst_simple + emp)
summary(delta11)

delta12 <- change12 %>%
  lm(formula = leisure_change ~ gender + emp)
summary(delta12)


delta4 <- change4 %>%
  lm(formula = leisure_change ~ gender+ new_educ+ nchild+ marst_simple)
summary(delta4)

delta3 <- change4 %>%
  lm(formula = leisure_change ~ gender+ new_educ+ nchild+ marst_simple)
summary(delta3)

delta <- change %>%
  lm(formula = leisure_change ~ gender+ new_educ+ child+ marst_simple)
summary(delta)

delta3 <- change3 %>%
  lm(formula = leisure_change ~ gender+ new_educ+ nchild+ marst_simple)
summary(delta3)



```

```{r table1, , results = "asis"}
stargazer(delta, delta3, title="Models for Change in Leisure", align=TRUE, type = "html")

```


```{r time-year-gender effects}


# First Set

time_model <- newcsv1 %>%
  filter(year < 2020) %>%
  mutate(year = as.character(year)) %>%
  lm(formula = bls_leis ~ gender + year + gender*year + age + race + new_educ,weights = wt06 ) 


# W employment
time_model1 <- newcsv1 %>%
  filter(year < 2020) %>%
  mutate(year = as.character(year)) %>%
  lm(formula = bls_leis ~ gender + year + gender*year + age + race + new_educ + emp, weights = wt06) 


# W emp*gender

time_model2 <- newcsv1 %>%
  filter(year < 2020) %>%
  mutate(year = as.character(year)) %>%
  lm(formula = bls_leis ~ gender + year + gender*year + age + race + new_educ + emp + emp*year, weights = wt06) 




```

```{r table2, results = "asis"}

stargazer(time_model, time_model1, time_model2, title="Models for Change in Leisure", align=TRUE, type = "html")

#stargazer(time_modela, time_model1a, time_model2a8, title="Models for Change in Leisure", align=TRUE, type = "html")
```


```{r}

newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2009) %>%
  summarize(median_bls_leis_arts = weighted.median(bls_leis_arts, wt06),
            median_bls_leis_attend = weighted.median(bls_leis_attend, wt06),
            median_bls_leis_attsport = weighted.median(bls_leis_attsport, wt06),
            median_bls_leis_partsport = weighted.median(bls_leis_partsport, wt06),
            median_bls_leis_relax = weighted.median(bls_leis_relax, wt06),
            median_bls_leis_soc = weighted.median(bls_leis_soc, wt06),
            median_bls_leis_sport = weighted.median(bls_leis_sport, wt06),
            median_bls_leis_soccom = weighted.median(bls_leis_arts, wt06),
            median_bls_leis_travel = weighted.median(bls_leis_travel, wt06),
            median_bls_leis_tv = weighted.median(bls_leis_tv, wt06)) %>%
  pivot_longer(cols = everything(), names_to = "Activity", values_to = "Median Weighted Daily Minutes") %>%
  kbl() %>%
  kable_styling()

newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2009) %>%
  summarize(mean_bls_leis_arts = weighted.mean(bls_leis_arts, wt06),
            mean_bls_leis_attend = weighted.mean(bls_leis_attend, wt06),
            mean_bls_leis_attsport = weighted.mean(bls_leis_attsport, wt06),
            mean_bls_leis_partsport = weighted.mean(bls_leis_partsport, wt06),
            mean_bls_leis_relax = weighted.mean(bls_leis_relax, wt06),
            mean_bls_leis_soc = weighted.mean(bls_leis_soc, wt06),
            mean_bls_leis_sport = weighted.mean(bls_leis_sport, wt06),
            mean_bls_leis_soccom = weighted.mean(bls_leis_arts, wt06),
            mean_bls_leis_travel = weighted.mean(bls_leis_travel, wt06),
            mean_bls_leis_tv = weighted.mean(bls_leis_tv, wt06)) %>%
  pivot_longer(cols = everything(), names_to = "Activity", values_to = "Mean Weighted Daily Minutes") %>%
  kbl() %>%
  kable_styling()

newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2009) %>%
  group_by(gender) %>%
  summarize(median_bls_leis_arts = weighted.median(bls_leis_arts, wt06),
            median_bls_leis_attend = weighted.median(bls_leis_attend, wt06),
            median_bls_leis_attsport = weighted.median(bls_leis_attsport, wt06),
            median_bls_leis_partsport = weighted.median(bls_leis_partsport, wt06),
            median_bls_leis_relax = weighted.median(bls_leis_relax, wt06),
            median_bls_leis_soc = weighted.median(bls_leis_soc, wt06),
            median_bls_leis_sport = weighted.median(bls_leis_sport, wt06),
            median_bls_leis_soccom = weighted.median(bls_leis_arts, wt06),
            median_bls_leis_travel = weighted.median(bls_leis_travel, wt06),
            median_bls_leis_tv = weighted.median(bls_leis_tv, wt06)) %>%
  pivot_longer(!gender, names_to = "Activity", values_to = "Median Weighted Daily Minutes") %>%
  kbl() %>%
  kable_styling()
  

newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2009) %>%
  group_by(emp, gender, new_educ, year) %>%
  summarize(median_bls_leis_arts = weighted.median(bls_leis_arts, wt06),
            median_bls_leis_attend = weighted.median(bls_leis_attend, wt06),
            median_bls_leis_attsport = weighted.median(bls_leis_attsport, wt06),
            median_bls_leis_partsport = weighted.median(bls_leis_partsport, wt06),
            median_bls_leis_relax = weighted.median(bls_leis_relax, wt06),
            median_bls_leis_soc = weighted.median(bls_leis_soc, wt06),
            median_bls_leis_sport = weighted.median(bls_leis_sport, wt06),
            median_bls_leis_soccom = weighted.median(bls_leis_arts, wt06),
            median_bls_leis_travel = weighted.median(bls_leis_travel, wt06),
            median_bls_leis_tv = weighted.median(bls_leis_tv, wt06)) %>%
  ggplot(mapping = aes(x = year, y = median, group = new_educ, colour = new_educ)) +
  geom_line() +
  facet_wrap(~gender + emp) +
  labs(
  title = "Daily individual leisure minutes",
  y = "Daily Minutes",
  x = "Count",
  caption = "Data from ATUS",
)

newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2009) %>%
  group_by(emp, gender, new_educ, year) %>%
  summarize(median_bls_leis_arts = weighted.mean(bls_leis_arts, wt06),
            median_bls_leis_attend = weighted.mean(bls_leis_attend, wt06),
            median_bls_leis_attsport = weighted.mean(bls_leis_attsport, wt06),
            median_bls_leis_partsport = weighted.mean(bls_leis_partsport, wt06),
            median_bls_leis_relax = weighted.mean(bls_leis_relax, wt06),
            median_bls_leis_soc = weighted.mean(bls_leis_soc, wt06),
            median_bls_leis_sport = weighted.mean(bls_leis_sport, wt06),
            median_bls_leis_soccom = weighted.mean(bls_leis_arts, wt06),
            median_bls_leis_travel = weighted.mean(bls_leis_travel, wt06),
            median_bls_leis_tv = weighted.mean(bls_leis_tv, wt06)) 

# TV Mean by Group   
newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2009) %>%
  group_by(emp, gender, new_educ, year) %>%
  summarize(mean_bls_leis_arts = weighted.mean(bls_leis_arts, wt06),
            mean_bls_leis_attend = weighted.mean(bls_leis_attend, wt06),
            mean_bls_leis_attsport = weighted.mean(bls_leis_attsport, wt06),
            mean_bls_leis_partsport = weighted.mean(bls_leis_partsport, wt06),
            mean_bls_leis_relax = weighted.mean(bls_leis_relax, wt06),
            mean_bls_leis_soc = weighted.mean(bls_leis_soc, wt06),
            mean_bls_leis_sport = weighted.mean(bls_leis_sport, wt06),
            mean_bls_leis_soccom = weighted.mean(bls_leis_arts, wt06),
            mean_bls_leis_travel = weighted.mean(bls_leis_travel, wt06),
            mean_bls_leis_tv = weighted.mean(bls_leis_tv, wt06)) %>%
  ggplot(mapping = aes(x = mean_bls_leis_tv, y = emp, colour = new_educ)) +
  geom_point() +
  facet_wrap(~ gender + new_educ) +
    labs(
  title = "Average minutes individuals spend on watching TV",
  y = "Employment Status",
  x = "Daily Minutes",
  caption = "Data from ATUS",
)

newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2009) %>%
  group_by(emp, gender, new_educ, year) %>%
  summarize(mean_bls_leis_arts = weighted.mean(bls_leis_arts, wt06),
            mean_bls_leis_attend = weighted.mean(bls_leis_attend, wt06),
            mean_bls_leis_attsport = weighted.mean(bls_leis_attsport, wt06),
            mean_bls_leis_partsport = weighted.mean(bls_leis_partsport, wt06),
            mean_bls_leis_relax = weighted.mean(bls_leis_relax, wt06),
            mean_bls_leis_soc = weighted.mean(bls_leis_soc, wt06),
            mean_bls_leis_sport = weighted.mean(bls_leis_sport, wt06),
            mean_bls_leis_soccom = weighted.mean(bls_leis_arts, wt06),
            mean_bls_leis_travel = weighted.mean(bls_leis_travel, wt06),
            mean_bls_leis_tv = weighted.mean(bls_leis_tv, wt06)) %>%
  ggplot(mapping = aes(x = mean_bls_leis_relax, y = emp, colour = new_educ)) +
  geom_point() +
  facet_wrap(~ gender + new_educ) +
  labs(
  title = "Average minutes individuals spend on relaxation",
  y = "Employment Status",
  x = "Daily Minutes",
  caption = "Data from ATUS",
)
  

newcsv1 %>%
  filter(year > 2006) %>%
  filter(year < 2009) %>%
  group_by(emp, gender, new_educ, year) %>%
  summarize(mean_bls_leis_arts = weighted.mean(bls_leis_arts, wt06),
            mean_bls_leis_attend = weighted.mean(bls_leis_attend, wt06),
            mean_bls_leis_attsport = weighted.mean(bls_leis_attsport, wt06),
            mean_bls_leis_partsport = weighted.mean(bls_leis_partsport, wt06),
            mean_bls_leis_relax = weighted.mean(bls_leis_relax, wt06),
            mean_bls_leis_soc = weighted.mean(bls_leis_soc, wt06),
            mean_bls_leis_sport = weighted.mean(bls_leis_sport, wt06),
            mean_bls_leis_soccom = weighted.mean(bls_leis_arts, wt06),
            mean_bls_leis_travel = weighted.mean(bls_leis_travel, wt06),
            mean_bls_leis_tv = weighted.mean(bls_leis_tv, wt06)) %>%
  ggplot(mapping = aes(x = mean_bls_leis_soc, y = emp, colour = new_educ)) +
  geom_point() +
  facet_wrap(~ gender + new_educ) +
  labs(
  title = "Average minutes individuals spend on socializing",
  y = "Employment Status",
  x = "Daily Minutes",
  caption = "Data from ATUS",
)
  

```

